# SPDX-FileCopyrightText: 2026 Alec Delaney
#
# SPDX-License-Identifier: MIT

name: Check memory of imports

on: [pull_request]

jobs:
  check-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Check memory
        id: check-memory
        uses: tekktrik/circuitpython-memory-check@main
        with:
          # TODO: Version should be the latest tag eventually
          version: 10.1.3
