# SPDX-FileCopyrightText: 2026 Alec Delaney
#
# SPDX-License-Identifier: MIT

name: Check memory of imports

on: [pull_request, push]

jobs:
  find-imports:
    runs-on: ubuntu-latest
    outputs:
      import-names: ${{ steps.find-imports.outputs.import-names }}
    steps:
    - name: Find imports
      id: find-imports
      uses: tekktrik/circuitpython-memory-check/find-imports@main
  
  check-memory:
    needs: find-imports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        import-name: ${{ fromJson(needs.find-imports.outputs.import-names) }}
    steps:
      - name: Check memory
        id: check-memory
        uses: tekktrik/circuitpython-memory-check/check-memory@main
        with:
          # TODO: Version should be the latest tag eventually
          version: 10.1.3
          import-name: ${{ matrix.import-name }}
